year: 2010
horizons: [30, 90, 180] # Horizons in days (including daily)

var: diabetes

spatial_res: zcta
temporal_res: daily

input_dir: data/input

#var_group
min_year: 2000
max_year: 2020
min_spatial_res: zcta
min_temporal_res: daily
lego_dir: lego/medicare_synthetic/
vg_name: ccw
lego_prefix: sparse_counts

# Debug options
debug: false
debug_days: 3  # Set to null or remove for full year processing

# Synthetic data parameters
synthetic:
  random_seed: 42               # Global random seed for reproducibility

  # Paths for ZCTA data
  zcta_unique_path: data/input/lego/geoboundaries/us_geoboundaries__census/us_uniqueid__census/zcta_yearly
  zcta_shapefile_path: data/input/lego/geoboundaries/us_geoboundaries__census/us_shapefile__census/zcta_yearly
  population_path: data/input/lego/social/demographics__census/raw/core/zcta__dec__population.parquet

  var_name: test
  poisson_params:
    base_rate: 0.11
    seasonal_amplitude: 0.02
    spatial_variance: 0.03
    latitude_effect: 0.2
    longitude_effect: 0.1
    population_effect: 0.0001
    population_normalizer: 0.0003  # Population scaling factor (per capita effect)
    random_seed: 42

  # Geographic constraints
  mainland_only: true           # Filter for continental US only
  

hydra:
  run:
    dir: logs/synthetic/${now:%Y-%m-%d}/${now:%H-%M-%S}