name: legoloaderX
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.11
  - snakemake=8.16
  - hydra-core=1.3.2
  - pandas=2.2.2
  - numpy
  - pyarrow=11.0.0
  - python-duckdb=0.9.2
  - pip
  - pip:
    - ipykernel
    - tqdm
    - xarray
    - torch