year: 2010
horizons: [30, 90, 180] # Horizons in days | must be in data

var: diabetes

spatial_res: zcta
temporal_res: daily

input_dir: data/input
output_dir: data/health

min_year: 2000
max_year: 2001
min_spatial_res: zcta
min_temporal_res: daily

vg_name: ccw
lego_prefix: sparse_counts
lego_dir: lego/medicare/

hydra:
  run:
    dir: logs/dataloader/${now:%Y-%m-%d}/${now:%H-%M-%S}
