year: 2010

var: diabetes

spatial_res: zcta
temporal_res: daily

input_dir: data/input
output_dir: data/health

min_year: 2000
max_year: 2021
valid_normalize: false
min_spatial_res: zcta
min_temporal_res: daily

vg_name: francesca_claudio_00 #ccw
lego_prefix: counts #parquet input prefix
lego_dir: lego/medicare/ #parquet input path

# Denominator input
denom_dir: mbsf_medpar_denom
denom_temporal_res: yearly
denom_prefix: counts
denom_value_col: n_bene

hydra:
  run:
    dir: logs/dataloader/${now:%Y-%m-%d}/${now:%H-%M-%S}
